FROM mirrors.tencent.com/moggyteam/debian:stable-slim

USER root

RUN apt-get update && \
    apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get install -y psmisc nodejs wget sudo procps telnet vim inetutils-ping net-tools htop libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgbm1 libasound2 libpangocairo-1.0-0 libxss1 libgtk-3-0

